### ISSUE TITLE
litle bug fixed

### ISSUE THREAD

**Issue by Den68** [dwilhelm89/Leaflet.StyleEditor#10]
create moooore div 'leaflet-styleeditor-tooltip-wrapper' .. and no delete it...
    addButtons: function() {
        var nextBtn = L.DomUtil.create('button', 'leaflet-styleeditor-button styleeditor-nextBtn', this.options.styleEditorHeader);
        nextBtn.title = 'Choose another element you want to style';

        L.DomEvent.addListener(nextBtn, 'click', function(e) {
        	this.hideEditor();
        	-------this.createTooltip();---- delete for this
        	e.stopPropagation();
        }, this);
    },

    createTooltip: function() {
        if (!this.options.showTooltip) {
        	return;
        }
	if( typeof this.options.tooltipwrap === 'undefined' ) {
        this.options.tooltipwrap = L.DomUtil.create('div', 'leaflet-styleeditor-tooltip-wrapper', document.body);
	}

	if(( typeof this.options.tooltip !== 'undefined' ) && ( this.options.tooltip !== null )) {
	this.options.tooltip.parentNode.removeChild(this.options.tooltip);
	this.options.tooltip = null;
	}
        this.options.tooltip = L.DomUtil.create('div', 'leaflet-styleeditor-tooltip', this.options.tooltipwrap);
	this.options.tooltip.innerHTML = 'Выберите элемент для редактирования стиля';
    },

    removeTooltip: function() {
        if (this.options.tooltip && this.options.tooltip.parentNode) {
		this.options.tooltip.parentNode.removeChild(this.options.tooltip);
		this.options.tooltip = null;
        }
    }

**Comment by fupduck** [comment]
@dwilhelm89 I guess you can close this now.
has been fixed by #19
