### ISSUE TITLE
Leaflet.StyleEditor.css has reference to https://unpkg.com

### ISSUE THREAD

**Issue by wggley** [dwilhelm89/Leaflet.StyleEditor#103]
https://unpkg.com/leaflet@0.7.7/dist/images/marker-icon-2x.png

https://github.com/dwilhelm89/Leaflet.StyleEditor/blob/cc2297f498e1b2d664d088cfaedeb1141ab3b837/dist/css/Leaflet.StyleEditor.css#L212

**Comment by fupduck** [comment]
wow. thanks for noticing.

**Comment by fupduck** [comment]
fixed in 0.1.20
