### ISSUE TITLE
Event when clicking the Style editor button

### ISSUE THREAD

**Issue by AlbertoMCS** [dwilhelm89/Leaflet.StyleEditor#111]
Hi, 
I would like to be able to do an action when clicking the editor button (the one which enables editing). 
I tried this but it did not work, 

```
$(".leaflet-control-styleeditor-interior").on('click', function(){
   alert('hello');
});
```
How can I do it?
Many thanks.

**Comment by fupduck** [comment]
hey @AlbertoMCS ,
if I understand correctly you are talking about the control icon? in the top right corner? (see [here](https://dwilhelm89.github.io/Leaflet.StyleEditor/))
if that is correct you should use `$('.leaflet-control-styleeditor-interior')` I think :)

**Comment by AlbertoMCS** [comment]
@fupduck yes, that's exactly the selector I am using, but not luck so far.

**Comment by AlbertoMCS** [comment]
@fupduck now is working, many thanks!
