### ISSUE TITLE
Can't update once line without update others

### ISSUE THREAD

**Issue by dgoujard** [dwilhelm89/Leaflet.StyleEditor#13]
In the demo with leaflet.draw when i have two polyline and use "Style editor" toolbar item, select one polyline and change color it's update all polyline.

**Comment by dwilhelm89** [comment]
You're right. Something one should investigate...

**Comment by dgoujard** [comment]
Found the "problem" it's StyleEditor default option "useGrouping" is set to true by default

**Comment by dwilhelm89** [comment]
Haha nice. Totally forgot about that option
