### ISSUE TITLE
styleEditor with leaflet draw

### ISSUE THREAD

**Issue by Stefdv** [dwilhelm89/Leaflet.StyleEditor#15]
when i draw a eg a circle and a rectangle, and then edit one of them with the styleeditor, both shapes change.

another question...is it possible to use the styleEditor functionality with the button from Leaflet.Draw or vice versa ?

**Comment by dwilhelm89** [comment]
> when i draw a eg a circle and a rectangle, and then edit one of them with the styleeditor, both shapes > change.

There is an option to group features together.
Try to initialize the Editor with:
````
var styleEditor = L.control.styleEditor({
    useGrouping: false
});
````

> another question...is it possible to use the styleEditor functionality with the button from Leaflet.Draw or vice versa ?

I'm not exactly sure what you mean by that?
