### ISSUE TITLE
When there are multiple objects on the map, the styling applies to all

### ISSUE THREAD

**Issue by joshting** [dwilhelm89/Leaflet.StyleEditor#17]
When drawing individual objects successively, each objects can be styled individually.  But if I close the form, trigger style editor, re-select one of the objects, the style will apply to all.  Checking the currentElement._layers, all layers (drawn objects) are in it.

**Comment by onyx00** [comment]
var styleEditor = L.control.styleEditor({
...
            useGrouping: false,
..
        });
