### ISSUE TITLE
Change default values

### ISSUE THREAD

**Issue by augustobg** [dwilhelm89/Leaflet.StyleEditor#22]
Hi, exactly where on the code can I change the default opacity values that appears on the side bar menu?

I tried on the js but didnt work, maybe not the correct line or place.

Can I have some help with that?

Thanks

**Comment by dwilhelm89** [comment]
The options are set in _Leaflet.StyleForms.js_ Starting from line 49 you can see that the value is set by the current value of the feature. If the feature does not have a value the default would be 1.
Leaflet has a default value of 0.5 for opacity, which is why this value is shown in the demo

**Comment by augustobg** [comment]
thanks, that helps :)
