### ISSUE TITLE
Style editor only works for one of the layers

### ISSUE THREAD

**Issue by abrobia** [dwilhelm89/Leaflet.StyleEditor#63]
I have a leaflet map with several layers (polylines and markers). Only one of the layers is active at the beginning; the rest are activated and added from layers control. The plugin works fine for the layer that is activated at the beginning, but it does not work for the rest of the layers. Any suggestions? Thanks.

**Comment by fupduck** [comment]
@abrobia How are you creating the layers?
Would you mind creating an [jsfiddle](https://jsfiddle.net/ ) to help me understand your issue?

**Comment by fupduck** [comment]
closing because missing information
