### ISSUE TITLE
How can I eliminate the Mapbox url's for the marker thumbnails?

### ISSUE THREAD

**Issue by poelerulf** [dwilhelm89/Leaflet.StyleEditor#69]
Congratulations to the great plugin!
In my offline environment, unfortunately, I can not upload images from the Internet. Is there a marker without this requirement or is there a way to host the preview-images myself?
Maybe you already have a marker for awesome markers?

**Comment by fupduck** [comment]
Hey there!
Sadly there is no option to host the current default markers yourself. I think it was a licensing problem.

I didn't invest more time into writing the AwesomeMarkers. And I actually do not recall it's last state.
But you can create your own Markers if you want to.
[AktionskartenMarker](https://github.com/KartographischeAktion/AktionskartenMarker) is the only implementation I have stumbled upon which might be used as an example to implement locally hosted markers.

Best regards and good luck!
