### ISSUE TITLE
Provide non-minified JS in releases

### ISSUE THREAD

**Issue by JeroenDeDauw** [dwilhelm89/Leaflet.StyleEditor#89]
This makes debugging easier when something goes wrong. It also makes it easier to look at the source.

**Comment by JeroenDeDauw** [comment]
I figure some changes/additions to https://github.com/dwilhelm89/Leaflet.StyleEditor/blob/master/webpack.config.js need to be made for this to happen but I'm not familiar with webpack and did not see an obvious way to do this while looking at the file for a few minutes.

**Comment by fupduck** [comment]
Transpiling the code actually is one of the mayor features why I introduced webpack - this will allow users with IE to use the code.

Alternatively you should be able to `import 'leaflet-styleeditor'` this should use the original files

**Comment by fupduck** [comment]
For debugging I would suggest checking out the repo opening `index.html` and running `npx webpack --watch --mode development`

**Comment by JeroenDeDauw** [comment]
I am not using node or webpack. (Due to the weird stack I have to deal with.)

My suggestion here is to additionally provide a non-minified version. Not to remove the minified one. Other Leaflet libraries I recently used all have a non-minified JS file in their releases. So I think this is a very valid feature request.

**Comment by fupduck** [comment]
Fixed by #96 
The next releases will contain an unminified version.
