### ISSUE TITLE
Cannot disable single form

### ISSUE THREAD

**Issue by JeroenDeDauw** [dwilhelm89/Leaflet.StyleEditor#90]
The docs in the README make it look like you can disable a single form. While this might be possible with some hacks, it is not as simple as the README makes it out to be.

```js
{'geometry': {'color': false}}
```

The above config does not just disable the `color` form, it disables ALL forms for `geometry`. This can be mitigated by specifying all other forms in the map, though this is IMO a hack.

**Comment by fupduck** [comment]
@JeroenDeDauw thanks for the bugreport - I will have a look - this should (and was) possible

**Comment by fupduck** [comment]
@JeroenDeDauw hope the updated README clarifies this.
