### ISSUE TITLE
Submit called when map in HTML form

### ISSUE THREAD

**Issue by Vayel** [dwilhelm89/Leaflet.StyleEditor#97]
Hi!

When the leaflet map is a child of an HTML form, clicking on the [`nextBtn`](https://github.com/dwilhelm89/Leaflet.StyleEditor/blob/1cd9092fc66cb5afc2987ad2a10449e8959097d5/src/javascript/Control.js#L185) calls the form submit (what we don't want).

To reproduce, just replace `<div id="map"></div>` by `<form><div id="map"></div></form>` in https://github.com/dwilhelm89/Leaflet.StyleEditor/blob/master/src/StyleEditorWithLeafletDraw.html and:

1. Draw a feature
2. Click on the top right button "Choose another element you want to style" to close the style editor
3. Watch the page reloading (because the form was submitted)

Thanks!

**Comment by Vayel** [comment]
Just calling `e.preventDefault()` in https://github.com/dwilhelm89/Leaflet.StyleEditor/blob/1cd9092fc66cb5afc2987ad2a10449e8959097d5/src/javascript/Control.js#L189 seems to fix the problem.

**Comment by fupduck** [comment]
thanks for reporting and fixing :)
